import myHeader from "./components/myHeader.js";
import myBanner from "./components/myBanner.js";
import myPosts from "./components/myPosts.js";
import myAside from "./components/myAside.js";
import myArticle from "./components/myArticle.js";
import myFooter from "./components/myFooter.js";
import myTable from "./components/myTable.js";
myHeader.show();
myBanner.showImage();
myBanner.show();
myAside.show();
myPosts.show();
myArticle.show();
myFooter.show();
myTable.show();