import myHeader from "./components/myHeader.js";
import myBanner from "./components/myBanner.js";
import myPosts from "./components/myPosts.js";
import myAside from "./components/myAside.js";
import myArticle from "./components/myArticle.js";
import myFooter from "./components/myFooter.js";
myHeader.show();
myBanner.showImage();
myBanner.show();
myAside.show();
myPosts.showPost();
myArticle.showArticle();
myArticle.showTable();
myFooter.showFooter();